name: CI/CI PIPELINE

on:
  push:
    branches: 
      -main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v4
    - name: Log into the Docker
    - uses: docker/login-action@v3.2.0
      with: 
        username: $ {{secrets.DOCKER_USERNAME}}
        password: $ {{secrets.DOCKER_PASSWORD}}
    - name: Build and push Docker images
    - uses: docker/build-push-action@v6.3.0
      with:
        context: .
        push: true
        tags: itnetsuraj/myrepofordemoproject:latest
          deploy: 
            runs-on: ubuntu-latest
            needs: bbuild
            steps: 
            - name: Deploy to Azure Web app
            - uses: Azure/webapps-deploy@v3.0.1
              with:
                app-name: ${{secrets.myappfordocker}}
                publish-profile:${{secrets.myappfordocker.PublishSettings}}
                images: itnetsuraj/myrepofordemoproject:latest
        
    
    
    
    
    
   
